/*
 *  Add Service Worker
 *  As the Service Worker generated by create-react-app only functions in the
 *  production version, this Service Worker has been added for use only in
 *  submitting the project in accordance with the rubric.
 */
export default function tempServiceWorker() {
      if ('serviceWorker' in navigator) {
          navigator.serviceWorker.register('/sw.js', {scope: '/'})
              .then(function(registration) {
                  console.log('Registration successful, scope is:', registration.scope);
              })
              .catch(function(error) {
                  console.log('Service worker registration failed, error:', error);
              });
      }
}
